### ISSUE TITLE
Change pricing to NPR

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#11]
Since saatobazaar represents nepali e-commerce site, It will be great on eye if price will be NPR.
All you need to do is multiply price by 100 or 150 and you're ready to go. But make sure calculations are correct. Cheers

**Comment by mit-anuj** [comment]
please assign me this issue

**Comment by Davidthecode** [comment]
@KriteshTimsina  where do you want to change prices to dollar cause i think prices are already in dollars

**Comment by KriteshTimsina** [comment]
Sorry for the confusion, I want to change it to NPR not dollar.

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina I'll be working on this issue. Kindly assign this issue to me

**Comment by KriteshTimsina** [comment]
Make sure to replace $ with Rs. 
Ex: Rs.500

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina See the changes in [PR](https://github.com/KriteshTimsina/sastobazaar-ecommerce/pull/12)
