### ISSUE TITLE
Cart total not updating

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#14]
-Try adding first product to cart
-Total becomes 13225
-now,add second items the total becomes 15000
-try removing second item from the cart
-the total stays the same

**Comment by KriteshTimsina** [comment]
@Itezaz-ul-Hassan

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Assign me this issue

**Comment by devham236** [comment]
hey @KriteshTimsina, i would love to work on this issue

**Comment by KriteshTimsina** [comment]
Feel free to work on it 🎉

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina @diwash007 Issue fixed in this [PR](https://github.com/KriteshTimsina/sastobazaar-ecommerce/pull/15)
