### ISSUE TITLE
Add about us page

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#19]
User can be able to go to about us page from footer.

Things to include:
- about sastobazaar
- how to contact
- map(optional)

**Comment by Raj-sharma01** [comment]
hello, i would like to work on this issue can you please assign it to me

**Comment by AhsanCommits** [comment]
Sure, I'll handle this. Users will be able to access the "About Us" page from the footer, including details about sastobazaar, contact information, and a map if available. I'll start working on it now if you assign me this issue.

@KriteshTimsina

**Comment by KriteshTimsina** [comment]
Sure feel free to work on it

**Comment by KriteshTimsina** [comment]
Any updates?

**Comment by Raj-sharma01** [comment]
I'm sorry, but the internet connection in my area has been very poor for
the past few days. I'm even unable to fork your repo. I'm unassigning
myself.

Once again, I sincerely apologize for not updating you earlier.

**Comment by KriteshTimsina** [comment]
No worries. Have fun

**Comment by KriteshTimsina** [comment]
@R4Rohit23 in case you'd like to work more on this project, here's one issue for you.

**Comment by rohit-chaware** [comment]
Is anybody still working on this issue or not.
