### ISSUE TITLE
Remove size select dropdown from Product and Cart page

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#2]
Remove size select dropdown as it doesn't make sense with some product.

To Do:
- remove size select from product and cart page.

**Comment by Faizanusmani06** [comment]
hey @KriteshTimsina I'll take this up.

**Comment by heisdinesh** [comment]
I can work on this @KriteshTimsina

**Comment by KriteshTimsina** [comment]
Make sure to work on a different branch and share screenshots here in comments after completion.

**Comment by heisdinesh** [comment]
Hey @KriteshTimsina could you add hactoberfest-accepted label to my PR so it would be considered as part of Hacktoberfest as well.

**Comment by KriteshTimsina** [comment]
Done. Hope it counts
