### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#20]
User must be able to go to FAQ page from footer link

-Add collapsable FAQ

**Comment by 12345rams** [comment]
assign me

**Comment by KriteshTimsina** [comment]
Sure!

**Comment by 12345rams** [comment]
what mistake occur in merge .Sir you can check tell me or you can edit app.js and Footer.js

**Comment by KriteshTimsina** [comment]
Merged. Thank you for your contribution
