### ISSUE TITLE
Revamp single product page on large screen

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#21]
Revamp single product page 
Make it look good
Here's the link to what i'm referring to
https://sastobazaar.netlify.app/product/5

**Comment by supunvindula** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by KriteshTimsina** [comment]
Have fun working on it

**Comment by supunvindula** [comment]
@KriteshTimsina Do you have any ideas for it?

**Comment by supunvindula** [comment]
Hi i have changed the single product page. Now it looks good. [You can access the PR from here](https://github.com/KriteshTimsina/sastobazaar-ecommerce/pull/28)

**Comment by KriteshTimsina** [comment]
Great . Your PR will be reviewed soon
