### ISSUE TITLE
Implement wishlist functionality

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#22]
When user clicks on heart, add that product to wishlist.

- display wishlist link in navbar
- add wishlist to localstorage
- wishlist should contain price and product detail from which they can add to cart directly
![image](https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/103115789/1784665f-0c3a-4b71-a629-70c6910a7ecb)

**Comment by Virtual4087** [comment]
I'd like to work on this. Can you assign this to me?

**Comment by KriteshTimsina** [comment]
Sure !

**Comment by Rohit-sharma04** [comment]
hey i would loke to work on this issue , could you please assign it to me

**Comment by BuilderPrid** [comment]
Hey just went through the repository once. If I am correct i think there's no database involved and this needs to be done using Contexts.
Could you assign this to me? I would love to make this contribution.

**Comment by KriteshTimsina** [comment]
Feel free to make your contribution.
