### ISSUE TITLE
No hacktoberfest title

### ISSUE THREAD

**Issue by BuilderPrid** [KriteshTimsina/sastobazaar-ecommerce#25]
@KriteshTimsina I think you may have forgotten to add hacktoberfest label to the repository and the hacktoberfest page is unable to access this. Please add the hacktoberfest label to the repo.

**Comment by KriteshTimsina** [comment]
How can I do that?

**Comment by BuilderPrid** [comment]
@KriteshTimsina I am not sure. Thought you should know. Is this repository not hacktoberfest accepted?

**Comment by KriteshTimsina** [comment]
Well the repository has the hactoberfest-accepted label. I think it is hacktoberfest accepted
