### ISSUE TITLE
Implement dark mode on Product detail and FAQ page

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#31]
Add dark mode classes to product detail pages and FAQ page.
Look for tailwind class dark:bg-darkbg for background and dark:darktext for text

**Comment by Devrishi-Dutta** [comment]
can I work on this issue?

**Comment by KriteshTimsina** [comment]
Sure. Feel free to work on it.

**Comment by Saurabhyadav0** [comment]
@Devrishi-Dutta  sir can you assing me this project

**Comment by Devrishi-Dutta** [comment]
> @Devrishi-Dutta sir can you assing me this project

I am a contributor , you have to ask the owner of the project for assigning issues .

**Comment by Saurabhyadav0** [comment]
who is the owner @KriteshTimsina ? 
sir can you assign me this project

**Comment by KriteshTimsina** [comment]
Sure . Feel free to work on it @Saurabhyadav0
