### ISSUE TITLE
Revamp Homepage

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#33]
Task to accomplish
-Make slider look better in mobile screen.
-add simple fade in animation.
-make it look better 
-add a map component

**Comment by Ahsan689** [comment]
Do you want to add map component for Swiper?

**Comment by KriteshTimsina** [comment]
Nope. I want to implement a map in homepage. 
Somewhat like,
Title: We're available all across Nepal
And Map below the title

**Comment by Ahsan689** [comment]
will you provide me google-map-api-key, which I have to implement in GoogeMap component and also latitude and longitude.

**Comment by KriteshTimsina** [comment]
Why don't you simply implement map using iframe. Wouldn't that be way way way easier 😅?

**Comment by KriteshTimsina** [comment]
here you go
<iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d114235.12194254225!2d87.99023850968474!3d26.525026722515186!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39e5ae61b2287b75%3A0xb7c984713b674197!2sBhadrapur!5e0!3m2!1sen!2snp!4v1685883004695!5m2!1sen!2snp"
                loading="lazy"
                className="w-full bg-black h-96"
              ></iframe>

**Comment by Ahsan689** [comment]
oh yeah sure, I will go with that. assign me
