### ISSUE TITLE
Page not found error on page reload [Production error]

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#34]
On production site [(https://sastobazaar.netlify.app)], When user reloads or refreshes the page, an page not found error occurs.
Is there any way to solve it. 

![image](https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/103115789/51715ced-b468-4cce-8379-0bcb2554d2ab)

**Comment by Ahsan689** [comment]
Hey I have found the solution for this and I want to try it,  can you assign me

**Comment by KriteshTimsina** [comment]
Make sure to test it on production environment
