### ISSUE TITLE
Pagination on mobile screen

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#35]
Place pagination right next to sort component in mobile screen

![IMG_20231030_202118.jpg](https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/103115789/4e2c3d17-a307-4e92-a0ad-46366048cd2c)

**Comment by ZaidMarrie** [comment]
Hi @KriteshTimsina, May I work on this?

**Comment by ZaidMarrie** [comment]
The two components are nested in two seperate parent elements. How would you like me to approach this, since the pagination is further down the page while the sort component is in a sidebar closer to the top of the page?

**Comment by KriteshTimsina** [comment]
You can implement it anyway you want to.
Two different div's for small screen and large one hidden while other is visible.Or, if there's the better way

**Comment by ZaidMarrie** [comment]
Yes, that is what I was thinking of doing. I want to conditionally render them depending on the screen. For the one on mobile can I make it wrap when there is not enough space between the Sort and Pagination Component?
