### ISSUE TITLE
 Add "Add to Wishlist" Option on Product Page

### ISSUE THREAD

**Issue by adarsh-site** [KriteshTimsina/sastobazaar-ecommerce#42]
I would like to suggest the addition of an "Add to Wishlist" option on the product page.

<img width="960" alt="image" src="https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/120160355/e3f639a5-8bc7-43cb-adff-e9f654eb439c">

**Comment by KriteshTimsina** [comment]
Sure. You may work on it.

**Comment by adarsh-site** [comment]
hlo @KriteshTimsina, I have created a pr. please check it and let me know feedback.
