### ISSUE TITLE
Design a responsive Footer

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/sastobazaar-ecommerce#7]
Reference:
large screen:
![image](https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/103115789/18d2e991-2be9-4937-9504-2f77693a3801)
mobile:
![image](https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/103115789/417d44c4-b807-45dd-a528-f3d150dc11bb)

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign

**Comment by KriteshTimsina** [comment]
Great! Assigned

**Comment by MachNiph** [comment]
Assign me^
