### ISSUE TITLE
UI improvements 

### ISSUE THREAD

**Issue by saurabhbakolia** [KriteshTimsina/sastobazaar-ecommerce#8]
![image](https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/78996216/4a820278-3709-427b-be7a-483cbc3dd66c)

I would to like to do some UI/UX improvements to this card. 
Specially this wishlist button and preview button. 

And also this card it not clickable. I should be clickable to make he user experience better.

**Comment by KriteshTimsina** [comment]
Go ahead.
And feel free to look into other issues,
You can design a footer as mentioned in issues section.

**Comment by saurabhbakolia** [comment]
![image](https://github.com/KriteshTimsina/sastobazaar-ecommerce/assets/78996216/a2902303-1c69-49cf-b05c-1844ae17a521)


I have changed it like this and now user can click on the image to navigate to the cart page.

**Comment by KriteshTimsina** [comment]
Great @saurabhbakolia . You may add an effect or alert when clicking on ♥️ icon. Maybe 'Added to Wishlist' or something.
Overall,LGTM.🎉

**Comment by saurabhbakolia** [comment]
Ok. And also I am thinking  to add one cart icon to the product  cart it self.

**Comment by KriteshTimsina** [comment]
That would be awesome. Maybe you could make that a different PR.

**Comment by saurabhbakolia** [comment]
Hey, Can you add it as hacktoberfest accepted. I am not able to see it as accepted.
